{
 "title": "NGINX Plus Dashboard",
 "description": "Nginx plus native observability, through the dynamic module api output nginx plus real-time status data, including global statistics, ssl status, server / location / upstream status, upstream server active health check results. Enhance the reliability of nginx plus business operation, you can Inherit to any environment, including kubernetes.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "job", "label": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job='$job'},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX INSTANCE Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(up{ job=\"$job\"}) by (instance) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginxplus_nginx_config_generation{ job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX INSTANCE HTTP Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginxplus_http_requests_current{job=\"$job\"}",
     "legendFormat": "Current {{instance}}"
    },
    {
     "expr": "irate(nginxplus_http_requests_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Request/s {{instance}}"
    }
   ]
  },
  {
   "title": "NGINX Plus Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginxplus_connections_active{job=\"$job\"}",
     "legendFormat": "curConn - {{instance}}"
    },
    {
     "expr": "irate(nginxplus_connections_accepted{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPS {{instance}}"
    },
    {
     "expr": "irate(nginxplus_connections_idle{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Idle {{instance}}"
    },
    {
     "expr": "irate(nginxplus_connections_dropped{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Drop - {{instance}}"
    }
   ]
  },
  {
   "title": "INSTANCE Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_nginx_config_generation{job='$job'})"
    }
   ]
  },
  {
   "title": "Server Zone Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_server_zone_requests{job='$job'})"
    }
   ]
  },
  {
   "title": "Location Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_location_zone_requests{job='$job'})"
    }
   ]
  },
  {
   "title": "Upstream Server Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_upstream_server_state{job='$job', server=~\".+\", upstream=~\".+\" } == 1) / count(nginxplus_upstream_server_state{job='$job'})"
    }
   ]
  },
  {
   "title": "Upstream Server Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_upstream_server_state{job='$job'})"
    }
   ]
  },
  {
   "title": "Upstream Server Unhealthy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_upstream_server_state{job='$job'} != 1 )"
    }
   ]
  },
  { "title": "Instance SSL Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "SSL Handshake Successfully",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "irate(nginxplus_ssl_handshakes{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Handshakes"
    },
    {
     "expr": "irate(nginxplus_ssl_session_reuses{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Session Reuses"
    }
   ]
  },
  {
   "title": "SSL Handshake Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "irate(nginxplus_ssl_handshake_timeout{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Handshake Timeout"
    },
    {
     "expr": "irate(nginxplus_ssl_handshakes_failed{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Handshake Failed"
    },
    {
     "expr": "irate(nginxplus_ssl_no_common_cipher{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "No Common Cipher"
    },
    {
     "expr": "irate(nginxplus_ssl_no_common_protocol{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "No Common Prototocol"
    },
    {
     "expr": "irate(nginxplus_ssl_peer_rejected_cert{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Rejected Cert"
    }
   ]
  },
  {
   "title": "SSL Verify Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "irate(nginxplus_ssl_verify_failures_expired_cert{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Expired Cert"
    },
    {
     "expr": "irate(nginxplus_ssl_verify_failures_no_cert{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "No Cert"
    },
    {
     "expr": "irate(nginxplus_ssl_verify_failures_other{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Other"
    },
    {
     "expr": "irate(nginxplus_ssl_verify_failures_revoked_cert{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Revoked Cert"
    },
    {
     "expr": "irate(nginxplus_ssl_verify_failures_hostname_mismatch{instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Hostname Mismatch"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Server Requests / Responses",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"1xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"2xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"3xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"4xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"5xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_requests{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(nginxplus_server_zone_requests{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"} [$__rate_interval]) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginxplus_server_zone_processing{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_received{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_server_zone_sent{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"}[$__range])) by (server_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Zone - HTTP TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_requests{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "{{server_zone}}"
    }
   ]
  },
  {
   "title": "SSL Handshake Successfully",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"handshakes\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Handshakes - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"session_reuses\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Session Reuses - {{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Zone - HTTP Response 1xx/2xx/3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"1xx\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "1xx - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"2xx\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "2xx - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"3xx\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "3xx - {{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Zone - HTTP Response 4xx/5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"4xx\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "4xx - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_responses{server_zone=~\".+\", code=\"5xx\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "5xx - {{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Zone - Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_received{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Bytes recvd {{server_zone}}"
    }
   ]
  },
  {
   "title": "Server Zone - Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_sent{server_zone=~\".+\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Bytes send {{server_zone}}"
    }
   ]
  },
  {
   "title": "SSL Handshake Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"handshake_timeout\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Timeout - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"handshakes_failed\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Failed - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"no_common_cipher\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "No cipher - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"no_common_protocol\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "No Proto - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl{server_zone=~\".+\", event=\"peer_rejected_cert\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Peer Rejected - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl_verify_failures{server_zone=~\".+\", verify_failure=\"expired_cert\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Expired Cert - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl_verify_failures{server_zone=~\".+\", verify_failure=\"no_cert\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "No Cert - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl_verify_failures{server_zone=~\".+\", verify_failure=\"other\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Other - {{server_zone}}"
    },
    {
     "expr": "irate(nginxplus_server_zone_ssl_verify_failures{server_zone=~\".+\", verify_failure=\"revoked_cert\", instance=\"$instance\", job=\"$job\"} [$__rate_interval])",
     "legendFormat": "Revoked Cert - {{server_zone}}"
    }
   ]
  },
  { "title": "Location Zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Location Requests / Responses",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_location_zone_responses{location_zone=~\".+\", code=\"1xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_responses{location_zone=~\".+\", code=\"2xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_responses{location_zone=~\".+\", code=\"3xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_responses{location_zone=~\".+\", code=\"4xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_responses{location_zone=~\".+\", code=\"5xx\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_requests{location_zone=~\".+\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(nginxplus_location_zone_requests{location_zone=~\".+\", instance=\"$instance\", job=\"$job\"} [$__range]) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_received{location_zone=~\".+\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(nginxplus_location_zone_sent{location_zone=~\".+\", instance=\"$instance\", job=\"$job\"}[$__range])) by (location_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upstream Zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Upstream Server State (De-duplication)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginxplus_upstream_server_state{server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}) by (upstream,server) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Server Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_upstream_server_state{job='$job', instance='$instance'})"
    }
   ]
  },
  {
   "title": "Upstream Server Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_upstream_server_state{job='$job', instance='$instance', server=~\".+\", upstream=~\".+\" } == 1) / count(nginxplus_upstream_server_state{job='$job', instance='$instance'})"
    }
   ]
  },
  {
   "title": "Upstream Server TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 66 },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_requests{server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{upstream}} - {{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Unhealthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_upstream_server_state{job='$job', instance='$instance'} != 1 )"
    }
   ]
  },
  {
   "title": "Upstream Server Resp 1xx/2xx/3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=\"1xx\", server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "1xx - {{upstream}} - {{server}}"
    },
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=\"2xx\", server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "2xx - {{upstream}} - {{server}}"
    },
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=\"3xx\", server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "3xx - {{upstream}} - {{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Resp 4xx/5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=\"4xx\", server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "4xx - {{upstream}} - {{server}}"
    },
    {
     "expr": "irate(nginxplus_upstream_server_responses{code=\"5xx\", server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "5xx - {{upstream}} - {{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Resp Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "nginxplus_upstream_server_response_time{server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{upstream}} - {{server}}"
    }
   ]
  },
  {
   "title": "Upstream Server Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_fails{server=~\".+\", upstream=~\".+\", instance=\"$instance\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{upstream}} - {{server}}"
    }
   ]
  }
 ]
}